[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    fastled/FastLED @ ^3.6.0
    majicdesigns/MD_Parola @ ^3.7.3
    majicdesigns/MD_MAX72XX @ ^3.5.1
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8.0
